export const portfolioVideos = [
    {
        id: 1,
        title: 'Combinações de Cores',
        description: 'Dicas de cores para seu cenário 🔥',
        filename: 'Combinações de cores para seu cenário 🔥🔥🔥.mp4',
        category: 'Dicas',
        likes: '2.4k',
        comments: '156',
        shares: '89',
    },
    {
        id: 2,
        title: 'Dicas para Criadores',
        description: 'Essenciais para criadores de conteúdo',
        filename: 'DICAS PARA CRIADORES DE CONTEÚDO🔥#filmmaker #edicao #videomaker #edicaodevideo #criaçãodeconteú.mp4',
        category: 'Tutorial',
        likes: '3.1k',
        comments: '234',
        shares: '145',
    },
    {
        id: 3,
        title: 'Seja Referência',
        description: 'Como se tornar referência no mercado 💪',
        filename: 'Quer ser referência… faça isso! 🔥🔥#videomaker #criaçãodeconteúdo #edicao.mp4',
        category: 'Inspiração',
        likes: '5.2k',
        comments: '412',
        shares: '287',
    },
    {
        id: 4,
        title: 'Edição no CapCut',
        description: 'Removendo pausas da fala',
        filename: 'REMOVENDO PAUSAS DA SUA FALA NO CAPCUT🔥.mp4',
        category: 'Tutorial',
        likes: '1.8k',
        comments: '98',
        shares: '67',
    },
    {
        id: 5,
        title: 'HI-FI ou LO-FI',
        description: 'Qual a sua escolha? 🔥',
        filename: 'HI-FI OU LO-FI... QUAL A SUA ESCOLHA🔥🔥.mp4',
        category: 'Dicas',
        likes: '3.8k',
        comments: '267',
        shares: '178',
    },
    {
        id: 6,
        title: 'Igual um Robozinho',
        description: 'Automação na edição 🤖',
        filename: 'Igual um robozinho 🔥🔥.mp4',
        category: 'Tutorial',
        likes: '2.1k',
        comments: '145',
        shares: '92',
    },
    {
        id: 7,
        title: 'Clareza é Tudo',
        description: 'Quando você tem clareza de onde quer chegar',
        filename: 'Quando você tem clareza de onde quer chegar, a última coisa que você vai pensar é no julgamento .mp4',
        category: 'Inspiração',
        likes: '6.4k',
        comments: '521',
        shares: '342',
    },
    {
        id: 8,
        title: 'Tu Nunca Vai Sair do Lugar',
        description: 'Motivação para criadores 🔥',
        filename: 'Tu nunca vai sair do lugar!! 🔥🔥 #videomaker #criaçãodeconteúdo #edicao.mp4',
        category: 'Inspiração',
        likes: '4.7k',
        comments: '389',
        shares: '256',
    },
    {
        id: 9,
        title: 'Projeto Premium',
        description: 'Audiovisual de alta qualidade 🎬',
        filename: 'AQMbvtmTy5mjAyPhl8wytwTyQRPPu0UfwNMW-UufTy-bKLKCk0eJmvD55Z78gGPAdglApjH3Jn6fbui4HNK7Ms7kpCMGBu7K.mp4',
        category: 'Projeto',
        likes: '3.2k',
        comments: '198',
        shares: '134',
    },
    {
        id: 10,
        title: 'Projeto Especial',
        description: 'Conteúdo audiovisual profissional 🎬',
        filename: 'AQNaxBYC3o5dk8-HdStuNdIF7IxalCcKo0NIQHIorx6eAfsCjrvoCeJx3WL4ONT3nyz7oNbEM0Ifzp-kOfj68ibJtMsUeQWS.mp4',
        category: 'Projeto',
        likes: '4.3k',
        comments: '321',
        shares: '198',
    },
];
