export const portfolioVideos = [
    {
        id: 1,
        title: 'Combinações de Cores',
        description: 'Dicas de cores para seu cenário 🔥',
        filename: 'video-01.mp4',
        category: 'Dicas',
        likes: '2.4k',
        comments: '156',
        shares: '89',
    },
    {
        id: 2,
        title: 'Edição no CapCut',
        description: 'Removendo pausas da fala',
        filename: 'video-02.mp4',
        category: 'Tutorial',
        likes: '1.8k',
        comments: '98',
        shares: '67',
    },
    {
        id: 3,
        title: 'HI-FI ou LO-FI',
        description: 'Qual a sua escolha? 🔥',
        filename: 'video-03.mp4',
        category: 'Dicas',
        likes: '3.8k',
        comments: '267',
        shares: '178',
    },
    {
        id: 4,
        title: 'Igual um Robozinho',
        description: 'Automação na edição 🤖',
        filename: 'video-04.mp4',
        category: 'Tutorial',
        likes: '2.1k',
        comments: '145',
        shares: '92',
    },
    {
        id: 5,
        title: 'Clareza é Tudo',
        description: 'Quando você tem clareza de onde quer chegar',
        filename: 'video-05.mp4',
        category: 'Inspiração',
        likes: '6.4k',
        comments: '521',
        shares: '342',
    },
    {
        id: 6,
        title: 'Projeto Premium',
        description: 'Audiovisual de alta qualidade 🎬',
        filename: 'video-06.mp4',
        category: 'Projeto',
        likes: '3.2k',
        comments: '198',
        shares: '134',
    },
    {
        id: 7,
        title: 'Projeto Especial',
        description: 'Conteúdo audiovisual profissional 🎬',
        filename: 'video-07.mp4',
        category: 'Projeto',
        likes: '4.3k',
        comments: '321',
        shares: '198',
    },
];
